openapi: 3.0.3
info:
  title: Identification API
  description: |-
    This API provides face identification
#  termsOfService: http://swagger.io/terms/
#  contact:
#    email: apiteam@swagger.io
#  license:
#    name: Apache 2.0
#    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
#externalDocs:
#  description: Find out more about Swagger
#  url: http://swagger.io
servers:
  - url: http://localhost/api/v1
tags:
  - name: face
    description: Face identification
#    externalDocs:
#      description: Find out more
#      url: http://swagger.io

paths:
  /face:
    post:
      tags:
        - face
      summary: Request a face identification
      description: Request a face identification
      operationId: getUserByFace
      requestBody:
        description: Identify a user by his/her face
        content:
          image/png:
            schema:
              type: string
              format: binary
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
        '403':
          description: Forbiden
        '404':
          description: Not found
      security:
        - face_auth:
            - read:faces
  
  
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: theUser
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        email:
          type: string
          example: john@email.com
        phone:
          type: string
          example: '12345'
      xml:
        name: user
    
  securitySchemes:
    face_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://petstore3.swagger.io/oauth/token
          scopes:
            read:faces: read faces
    api_key:
      type: apiKey
      name: api_key
      in: header